#pragma once

#include <memory>
#include <mlir/Pass/Pass.h>

namespace rust_compiler::optimizer {

#define GEN_PASS_DECL_TEST
#define GEN_PASS_DECL_ATTRIBUTER
#define GEN_PASS_DECL_REWRITEPASS
#define GEN_PASS_DECL_LOWERAWAITPASS
#define GEN_PASS_DECL_LOWERERRORPROPAGATIONPASS
#define GEN_PASS_DECL_SUMMARYWRITERPASS
#define GEN_PASS_DECL_GVNPASS
#define GEN_PASS_DECL_DEADCODEELIMINATIONPASS
#define GEN_PASS_DECL_DEADSTOREELIMINATIONPASS
#define GEN_PASS_DECL_SCCPPASS
#define GEN_PASS_DECL_HIRLICMPASS
#define GEN_PASS_DECL_CONVERTHIRTOMIRPASS
#define GEN_PASS_DECL_CONVERTMIRTOLIRPASS
#define GEN_PASS_DECL_CONVERTLIRTOLLVMPASS
#define GEN_PASS_DECL_LOOPPASS
#define GEN_PASS_DECL_DEADARGUMENTELIMINATIONPASS
#define GEN_PASS_DECL_FUNCSPECIALPASS
#define GEN_PASS_DECL_MEMORYANALYSISPASS
#include "Optimizer/Passes.h.inc"

// declarative passes
#define GEN_PASS_REGISTRATION
#include "Optimizer/Passes.h.inc"

} // namespace rust_compiler::optimizer
